# Generated by Django 2.2.12 on 2020-09-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
                ('units', models.IntegerField()),
            ],
        ),
    ]
