# Generated by Django 2.2.12 on 2020-10-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmodel',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Subject Name'),
        ),
    ]
